---
title: "Ebola Situation Report"
output: word_document
date: "Last compiled on: `r format(Sys.time(), '%d %B, %Y')`"
params: 
 district: "Bolo" 
 date: "`r format(Sys.time(), '%d %B, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

# Define report parameters  

```{r }
date <- params$date
```


## Install packages

```{r}
pacman::p_load(
     rio,
     here,
     janitor,
     epikit,
     apyramid,
     lubridate,
     gtsummary,
     scales,
     gghighlight,
     ggExtra,
     flextable,
     tidyverse
)
```


## Import data

```{r}
# Import each dataset

# surveillance
surv_raw <- rio::import(here("data", "surveillance_linelist_12012014.csv"))

# hospital datasets
hosp_central  <- rio::import(here("intro_course", "data", "raw", "hospitals", "20141201_hosp_central.csv"))
hosp_military <- rio::import(here("intro_course", "data", "raw", "hospitals", "20141201_hosp_military.csv"))
hosp_other    <- rio::import(here("intro_course", "data", "raw", "hospitals", "20141201_hosp_other.csv"))
hosp_port     <- rio::import(here("intro_course", "data", "raw", "hospitals", "20141201_hosp_port.csv"))
hosp_smmh     <- rio::import(here("intro_course", "data", "raw", "hospitals", "20141201_hosp_smmh.csv"))
hosp_missing  <- rio::import(here("intro_course", "data", "raw", "hospitals", "20141201_hosp_missing.csv"))

# laboratory dataset
lab <- rio::import(here("intro_course", "data", "raw", "lab_results_20141201.xlsx"))

# case investigation dataset
investigations <- rio::import(here("intro_course", "data", "raw", "case_investigations_20141201.xlsx"))
```


## R Markdown

Today's district is `r params$district` and today's date is `params$date`. 

## Clean the surveillance linelist

```{r}
surv <- surv_raw %>% 
  
  # automatically clean column names
  clean_names() %>% 
  
  # manually clean column names   
  rename(
    date_onset = onset_date,
    date_report = date_of_report,
    district_res = adm3_name_res,
    district_det = adm3_name_det) %>%
     
  # remove unnecessary column
  select(-row_num) %>% 

  # de-duplicate rows  
  distinct() %>% 
     
  # convert date_onset to date class
  mutate(date_onset = mdy(date_onset)) %>% 
  mutate(date_report = mdy(date_report)) %>% 
     
  # create epiweek columns  
  mutate(week_onset = floor_date(date_onset, unit = "week")) %>% 
  mutate(week_report = floor_date(date_report, unit = "week")) %>% 
     
  # convert age to numeric class
  mutate(age = as.numeric(age)) %>% 
     
  # properly record missing values
  mutate(across(.cols = where(is.character), .fns = na_if, "")) %>% 
     
  # Make date-difference column  
  mutate(diff = date_report - date_onset) %>% 
     
  # convert negative values to NA
  mutate(wt_kg = ifelse(wt_kg < 0, NA, wt_kg),
         bmi   = ifelse(bmi < 0,   NA, bmi)) %>% 
     
  # convert gender values to full words
  mutate(gender = case_when(               # re-define gender as: 
    gender == 'm' ~ 'male',                # when "m", change to "male"   
    gender == 'f' ~ 'female',              # when "f", change to "female" 
    TRUE          ~ gender)) %>%           # any other value, remain as before
     
  # create age-in-years
  mutate(age_years = case_when(
    age_unit == "years"  ~ age,            # if age is given in years
    age_unit == "months" ~ age/12,         # if age is given in months
    is.na(age_unit)      ~ age,            # if age unit is missing, assume years
    TRUE                 ~ NA_real_)) %>%  # any other circumstance, assign missing
       
  # create age category column
  mutate(age_cat = age_categories(         # create new column
    age_years,                             # numeric column to make groups from
    lower = 0,
    upper = 70,
    by = 10)) %>% 
     
  # create column marking TRUE if district of residence and detection differ
  mutate(moved = district_res != district_det) %>% 
  
  # create new column that prioritizes district of detection
  mutate(district = coalesce(district_det, district_res)) %>% 
  
  # re-code hospital column
  mutate(hospital = recode(hospital,
    # for reference: OLD = NEW
    "Mitilary Hospital"  = "Military Hospital",
    "Port"               = "Port Hospital",
    "Port Hopital"       = "Port Hospital",
    "St. Mark's Maternity Hospital (SMMH)" = "SMMH")) %>% 
     
  # remove suspect cases
  filter(case_def == "Confirmed")
```


# Joins to other datasets 


## Create the hospital linelist

Bind together the different hospital linelists  

```{r}
# bind the rows 
hosp <- bind_rows(hosp_central, hosp_port, hosp_military, hosp_smmh, hosp_other, hosp_missing)
```

Clean the hospital linelist and join it to the surveillance dataset  

```{r}
# Modify the hosp dataset
hosp <- hosp %>% 
  # select specific columns from hosp, and re-name ID as case_ID
  select(
    case_id = ID,               # select and rename
    `hospitalisation date`,     # select
    `admission time`,           # select
    `outcome date`,             # select
    outcome)                    # select

# Join the two data frames with a full-join
combined <- full_join(surv, hosp, by = "case_id")
```


```{r}
# Join the two data frames with a full-join
# (place this in the Joining data section of your script)
combined <- full_join(combined, lab, by = "case_id")

```


```{r}

# keep only certain columns  
# (add to the Joining data section of your R script)
investigations <- investigations %>% 
  select(-c(age, `age unit`, gender))

# Join the two data frames with a full-join
combined <- full_join(combined, investigations, by = "case_id")
```



```{r}
# Clean the new columns that have been joined to 'combined'
combined <- combined %>% 
  
  # convert all column names to lower case and remove spaces
  clean_names() %>% 
  
  # edit names of new date columns
  rename(date_hospitalisation = hospitalisation_date,
         date_outcome         = outcome_date,
         date_infection       = infection_date) %>% 
  
  # covert new columns to class date
  mutate(date_hospitalisation = mdy(date_hospitalisation),
         date_outcome         = mdy(date_outcome),
         date_infection       = ymd(date_infection))
```



```{r}
export(combined, here("data", "linelist_combined_20141201.rds"))
```




<!-- ```{r} -->
<!-- # Clean medical linelist -->
<!-- ######################## -->
<!--              # bind together the different hospital files -->
<!-- med_clean <- bind_rows(central, military, missing, smmh, port, other) %>%   -->

<!--      # clean column names - lowercase, underscores, etc. -->
<!--      clean_names() %>% -->

<!--      # rename -->
<!--      rename( # NEW name    # OLD name -->
<!--              date_hospitalisation = "hospitalisation_date", -->
<!--              date_outcome = "outcome_date", -->
<!--              time_admission = "admission_time") %>% -->

<!--      # deduplicate -->
<!--      distinct() %>%  -->

<!--      # Make new columns -->
<!--      mutate( -->
<!--           across(contains("date"), ymd), -->

<!--           hour_admit = hour(strptime(time_admission, format = "%H:%M")),  -->
<!--           time_period = case_when( -->
<!--               hour_admit > 06  & hour_admit < 12 ~ "Morning", -->
<!--               hour_admit >= 12 & hour_admit < 17 ~ "Afternoon", -->
<!--               hour_admit >= 17 & hour_admit < 21 ~ "Evening", -->
<!--               hour_admit >= 21 | hour_admit <= 6 ~ "Night")) -->
<!-- ``` -->




<!-- ```{r} -->
<!-- # Clean case investigation dataset -->
<!-- ################################## -->
<!-- source_clean <- source_raw %>%  -->

<!--      # clean column names - lowercase, underscores, etc. -->
<!--      clean_names() %>% -->

<!--      # rename -->
<!--      rename( # NEW name    # OLD name -->
<!--              date_infection = "infection_date") %>% -->

<!--      # deduplicate -->
<!--      distinct() %>%  -->

<!--      # Make new columns -->
<!--      mutate(across(contains("date"), ymd)) -->
<!-- ``` -->




<!-- ```{r} -->
<!-- # Clean lab dataset -->
<!-- ################### -->
<!-- lab_clean <- lab_raw %>%  -->

<!--      # clean column names - lowercase, underscores, etc. -->
<!--      clean_names() %>% -->

<!--      # deduplicate -->
<!--      distinct() -->

<!-- # TODO could put TRUE/FALSE here with some higher than 40 -->
<!-- ``` -->






## Person

```{r}

age_pyramid(
     data = cases,
     age_group = "age_cat",
     split_by = "gender",
     proportional = TRUE,
     show_midpoint = FALSE)+
     
     theme_minimal()+
     
     labs(title = str_glue("Confirmed cases"),
          x = "",
          y = "",
          caption = str_glue(""),
          fill = "Gender")+
     
     scale_fill_discrete(labels = c("f" = "Female",
                                    "m" = "Male"))


```



## Time

```{r}

# define weekly breaks from Monday before first case
# Sequence of weekly Monday dates for CENTRAL HOSPITAL

# Monday prior to first case
monday_floor <- floor_date(min(cases$date_onset, na.rm=T),   "week", week_start = 1)

# Monday after last case
monday_ceiling <- ceiling_date(max(cases$date_onset, na.rm=T), "week", week_start = 1)

# define sequence of Mondays for histogram breaks
weekly_breaks <- seq.Date(
  from = monday_floor, # monday before first case
  to   = monday_ceiling, # monday after last case
  by   = "week")

# Make epidemic curve
ggplot(data = cases)+
       geom_histogram(
          mapping = aes(x = date_hospitalisation),
          breaks = weekly_breaks,
          closed = "left")+
     
       # x-axis labels
       scale_x_date(
         expand            = c(0,0),           # remove excess x-axis space before and after case bars
         date_breaks       = "4 weeks",        # date labels and major vertical gridlines appear every 3 Monday weeks
         date_minor_breaks = "week",           # minor vertical lines appear every Monday week
         labels = scales::label_date_short())+ # automatically efficient date labels
       
       # y-axis
       scale_y_continuous(
         expand = c(0,0))+             # remove excess y-axis space below 0 (align histogram flush with x-axis)
       
       # aesthetic themes
       theme_minimal()+                # simplify plot background
       
       theme(
         plot.caption = element_text(hjust = 0,        # caption on left side
                                     face = "italic"), # caption in italics
         axis.title = element_text(face = "bold"))+    # axis titles in bold
       
       # labels including dynamic caption
       labs(
         title    = "Weekly incidence of cases (Monday weeks)",
         subtitle = "",
         x        = "Week of hospitalisation",
         y        = "Weekly incident cases reported",
         caption  = stringr::str_glue("n = {nrow(cases)} cases; Hospitalisations range from {format(min(cases$date_onset, na.rm=T), format = '%a %d %b %Y')} to {format(max(cases$date_onset, na.rm=T), format = '%a %d %b %Y')}\n{nrow(cases %>% filter(is.na(date_onset)))} cases missing date of onset and not shown"))
```



## Place

```{r}
cases %>% 
     mutate(location = fct_explicit_na(location, na_level = "Missing")) %>% 
     tabyl(location) %>% 
     arrange(desc(n)) %>% 
     mutate(percent = scales::percent(percent, 1)) %>% 
     qflextable()
```









