---
title: "Situation Report"
subtitle: "Ebola outbreak in Sierra Leone"
author: "(Your name or agency here)"
output: 
  html_document:
    code_folding: hide
date: "`r Sys.Date()`"
params:
  district: "West II"
  publish_date: "2014-12-01"
---


```{r}

```




Spotlight on district: `r params$district`.  

```{r}
pacman::p_load(rio, here, tidyverse, janitor)

surv_raw <- import(here("intro_course", "surveillance_linelist_20141201.csv"))

surv_raw %>% 
     tabyl(adm3_name_res, adm3_name_det)

surv <- surv_raw %>% 
  
  # automatically clean column names
  clean_names() %>% 
  
  # manually clean column names   
  rename(
    date_onset = onset_date,
    date_report = date_of_report,
    district_res = adm3_name_res,
    district_det = adm3_name_det) %>%
     
  # remove unnecessary column
  select(-row_num) %>% 

  # de-duplicate rows  
  distinct() %>% 
     
  # convert date_onset to date class
  mutate(date_onset = mdy(date_onset)) %>% 
  mutate(date_report = mdy(date_report)) %>% 
     
  # create epiweek columns  
  mutate(week_onset = floor_date(date_onset, unit = "week", week_start = 1)) %>% 
  mutate(week_report = floor_date(date_report, unit = "week", week_start = 1)) %>% 
     
  # convert age to numeric class
  mutate(age = as.numeric(age)) %>% 
     
  # properly record missing values
  mutate(across(.cols = where(is.character), .fns = na_if, "")) %>% 
     
  # Make date-difference column  
  mutate(diff = date_report - date_onset)



combined <- import(here("intro_course", "data", "clean", "linelist_combined_20141201.rds"))

combined %>% 
     filter(district == params$district) %>% 
     drop_na(outcome) %>% 
     tabyl(hospital, outcome) %>% 
     adorn_totals("both")
```

